apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-calc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pi-calc
  template:
    metadata:
      labels:
        app: pi-calc
    spec:
      containers:
      - name: pi-calc
        image: localhost:500/pi-calc:latest
        imagePullPolicy: Always
        command: ["python"]
        args: ["pi_calc.py", "1000000"]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pi-calc
spec:
  type: NodePort
  selector:
    app: pi-calc
  ports:
  - name: http
    port: 80
    targetPort: 80

